#!/bin/bash

if [ ! -f "data.json" ]; then
	  echo "Error: data.json not found. Please run apiAutomation-0x00 first."
	    exit 1
fi

name=$(jq -r '.name' data.json)
type=$(jq -r '.types[0].type.name' data.json)
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)

name_capitalized=$(echo "$name" | sed 's/./\u&/')
formatted_weight=$(echo "$weight" | awk '{print $1 / 10}')
formatted_height=$(echo "$height" | awk '{print $1 / 10}')

echo "$name_capitalized is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
